### ISSUE TITLE
is this library compatible with xcode 8 and swift 3?

### ISSUE THREAD

**Issue by swabzz** [FuckBoilerplate/OkDataSources#3]
Hello,
Today I migrate to Xcode 8.0 and Swift 3.0 and there are bunch of errors in library.
is this library compatible with swift 3?

**Comment by robertofrontado** [comment]
Hello @bagwanshoaib,

Not yet, but @Reprazent made a [PR](https://github.com/robertofrontado/OkDataSources/pull/2) with the migration to swift 3, I'm still reviewing it but for sure is going to be published this week

**Comment by robertofrontado** [comment]
It is now, but I'm having an issue pushing it to cocoapods, but with carthage it should works

**Comment by robertofrontado** [comment]
@swabzz There's a new release [v1.0.0](https://github.com/robertofrontado/OkDataSources/releases/tag/1.0.0) that is compatible with Swift 3 👍, closing this issue
