### ISSUE TITLE
Problem in IB Designables

### ISSUE THREAD

**Issue by swabzz** [FuckBoilerplate/OkDataSources#4]
Hello,

I am getting bellow error when i am loading project.

.storyboard: error: IB Designables: Failed to update auto layout status: dlopen(OkDataSources.framework, 1): Library not loaded: @rpath/RxSwift.framework/RxSwift
  Referenced from: OkDataSources.framework
  Reason: image not found

Please take a look,
Thanks in advance

**Comment by robertofrontado** [comment]
@swabzz Make sure that in your storyboard, where you are using one of `OkDataSources` views, you have the Module set as well, i.e:

<img width="262" alt="screen shot 2017-01-07 at 10 52 44 am" src="https://cloud.githubusercontent.com/assets/11177510/21740887/8d90842e-d4c7-11e6-850c-b523a8f2e9ea.png">

**Comment by swabzz** [comment]
@rob

Yes i have set that option as you suggested. still there is same warning
<img width="260" alt="screen shot 2017-01-09 at 10 36 17 am" src="https://cloud.githubusercontent.com/assets/15198865/21757622/95ae2562-d657-11e6-82b0-2468cd945378.png">

**Comment by robertofrontado** [comment]
@swabzz I can see that you have `OkDataSources` but in this case it should be `OkDataSource` without the last `s`, my bad

**Comment by swabzz** [comment]
Thanks @rob
Will set as suggested and let you know

**Comment by robertofrontado** [comment]
@swabzz Closing this issue, feel free to open if it doesn't work for you
